### ISSUE TITLE
Handle shared memory areas in the File plugin

### ISSUE THREAD

**Issue by karya0** [dmtcp/dmtcp#156]
There is a race if two processes, that have a shared memory area backed by an unlinked file, are restarting at the same time.  It's possible that the first process creates, mmaps, and unlinks the file before the second process has a chance to use that file. In that case, the second process will create a new file, mmap it and then unlink it. Even though both of them have mapped the file as shared, the two memory regions refer to two different inodes and thus the file is not truly shared.  A proper fix would require synchronization between all restarting processes and thus the file plugin is a better place to handle shared memory areas.

This issue is somewhat related to #68.

**Comment by jiajuncao** [comment]
I assume the race condition happens in mtcp_restart(), since the file plugin handles the fd correctly. The only problem is the shared memory area. I tried the patch from #154, and it didn't work. I do agree that adding the synchronization in the file plugin is reasonable and less difficult to implement.

BTW, do we use the same logic to handle shared area opened by shm_open()?

**Comment by gc00** [comment]
See issue #167 for more on exhibiting this bug via shared-memory1.
