### ISSUE TITLE
Replace DMTCP_HOST/PORT with DMTCP_COORD_HOST/PORT

### ISSUE THREAD

**Issue by karya0** [dmtcp/dmtcp#22]
DMTCP_HOST/PORT are confusing and should be changed to DMTCP_COORD_HOST/PORT.  We should also make appropriate changes to the commandline flag.

**Comment by gc00** [comment]
Good point!  I assume we keep -h and -p.  Should we have three synonymous flags and two environment variables temporarily for backward compatibitity?
-h --host --coord-host
DMTCP_HOST DMTCP_COORD_HOST
and the same for ports?
I'll volunteer to create the pull request.  Is that the right spec?  (In a future release, we can remove DMTCP_HOST and DMTCP_PORT, but we'll keep it for DMTCP 2.4.0.)

**Comment by gc00** [comment]
For testing, we'll need to test for `dmtcp_launch --no-coordinator`, as well as `dmtcp_launch -p0`, and the combination of the two.  Similarly, need to test for `dmtcp_restart -p0`, and we need to test `dmtcp_coordinator` and `dmtcp_command`.  Note also that what DMTCP does with DMTCP_HOST/PORT environment variables currently is rather haphazard.  Also, after `dmtcp_restart --port XX`, when we call `mtcp_restart`, we revert back to the previous environment variables or information in the `SharedData` area.

**Comment by gc00** [comment]
This issue has now been fixed by pull request #92.

However, notice that issue #93 has now been opened, due to a related issue that affects dmtcp_restart saving the old pre-ckpt  DMTCP_COORD_PORT in its memory, and then using the old value to re-connect to the coordinator in cases where the socket temporarily breaks.  This doesn't work if there is a new coordinator on a different port after restart.
