### ISSUE TITLE
--ckpt-open-files in 2.4.4 does not checkpoint or restore unlinked open files correctly

### ISSUE THREAD

**Issue by kwharrigan** [dmtcp/dmtcp#346]
Consider the example in under tests in: https://github.com/kwharrigan/dmtcp/tree/unlink_test

It is common w/ temporary files to open and immediately unlink them, so that they are deleted once the process exits.  I'm concerned this is not being handled quite right, or perhaps I'm expecting some behavior that is not designed.

For one, the unlinked file is not stored in the ckpt*_files folder.  This means, at minimum, that in a restarted process the file contents are incorrect (or non-existent?).  

In my tests, if I pause right after the launch and  checkpoint, and inspect the /proc/<pid>/fd entry, I see the deleted file entry.  I can, of course, cat the contents of the deleted entry while the process is still running (0,1,2,3,4 as expected).

However, upon restart, the file is not restored to the unlinked / deleted (yet still open) state.  There is a new file handle open, which is empty.  I can only assume downstream processes expected to read the contents of that file will see incorrect file contents, and thus the state of the process has not been recreated faithfully.  **EDIT: The previous is kind of a silly statement.  In case of `O_WRONLY`, obviously we won't be reading this file later.  However, there is still perhaps an edge case, and clearly the argument we haven't restored the process accurately to the checkpointed state.  ** 

Hopefully this all makes sense.  I'm happy to dig into it more but thought I'd report so we can work it in parallel.

**Comment by rohgarg** [comment]
@kwharrigan: See: https://github.com/dmtcp/dmtcp/blob/2.5/src/plugin/ipc/file/fileconnection.cpp#L580 
The if-clause prevents an unlinked file that was opened with `O_WRONLY` flag from being checkpointed. Other unlinked files are checkpointed by default, regardless of the `--checkpoint-open-files` flag (see line #588 in `fileconnection.cpp`). The if-clause was introduced in commit: 5c3dd0aa, and seems to be intentional, but I am not sure if I understand the reason behind it. 

(FYI: the file1 test  (`test/file1.c`) in the DMTCP test-suite does the same thing as your unlink_test.)

@karya0: do you happen to remember the rationale behind this?

**Comment by rohgarg** [comment]
@kwharrigan: After discussing with @karya0, I figured out problematic lines in the code. I'll create a patch for this soon.

**Comment by rohgarg** [comment]
Fixed via #349.
